const routes = {
  home: "/",
  course: "/course",
  quiz: "/quiz",
  contact: "/contact",
  profile: "/profile",
  login: "/login",
  register: "/register",

  dashboard: "/dashboard",
  logout: "/logout",
  settings: "/settings",
  enrolledCourses: "/enrolledCourses",

  dashboardInstructor: "/dashboardInstructor",
  coursesInstructor: "/coursesInstructor",
  quizzesInstructor: "/quizzesInstructor",
  profileInstructor: "/profileInstructor",
  createCourse: "/createCourse",
  updateCourse: "/updateCourse",
  createQuizzes: "/createQuizzes",
  updateQuiz: "/updateQuiz",
  createLesson: "/createLesson",
  createVideo: "/createVideo",
  videoDetail: "/videoDetail",
  createExam: "/createExam",
  quizDetail: "/quizDetail",
  createDocument: "/createDocument",
  updateDocument: "/updateDocument",

  courseDetail: "/courseDetail",
  lesson: "/lesson",
  quizGame: "/quizExam",
  quizResult: "/quizResult",
  updateQuestion: "/updateQuestion",

  courseStudent: "/courseStudent",
  createCourseStudent: "/createCourseStudent",
  quizStudent: "/quizStudent",
  createQuizStudent: "/createQuizStudent",
  flashcard: "/flashcard",
  createFlashcard: "/createFlashcard",
  flashcardDetail: "/flashcardDetail",
  createLessonStudent:"/createLessonStudent",
  createDocumentStudent: "/createDocumentStudent",
  createVideoStudent:"/createVideoStudent",
  updateDocumentStudent:"/updateDocumentStudent",
  videoDetailStudent: "/videoDetailStudent",
  updateCourseStudent:"/updateCourseStudent",
  quizDetailStudent: "/quizDetailStudent",
  createExamStudent:"/createExamStudent",
  updateQuizStudent:"/updateQuizStudent",
  updateQuestionStudent: "/updateQuestionStudent"
};
export default routes;
